export default [
  {
    "id": 1,
    "username": "swUsername1",
    "fullName": "Tom Hessburg",
    "password": "$2b$08$BM.F1zDzJBW4dXpuurc/guUEO2XcyhWkEIr2L1LTDRrZS.vOuVW8a",
    "photoUrl": "https://images.unsplash.com/photo-1505322747495-6afdd3b70760?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80",
    "serviceType": "bellhop",
    "timeAtJob": "2 years",
    "tagline": "A helping hand :)",
    "bio": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "workplace": "rusteak",
    "accountBalance": 150.5,
    "rating": 4.2,
    "numOfRatings": 52
  },
  {
    "id": 2,
    "username": "swUsername2",
    "fullName": "Jane Doe",
    "password": "$2b$08$qByy.Sa.6xh2XMOPvV8V1.ZsCsfaW60Pmkz4eEG5LXSA9hKyUgrx.",
    "photoUrl": "https://images.unsplash.com/photo-1505322747495-6afdd3b70760?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80",
    "serviceType": "Waitress",
    "timeAtJob": "1 year 2 months",
    "tagline": "Ill bring ya what you need!",
    "bio": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "workplace": "Avion",
    "accountBalance": 220.72,
    "rating": 4.81,
    "numOfRatings": 27
  },
  {
    "id": 3,
    "username": "singerguy57",
    "fullName": "Jim Jones",
    "password": "$2b$08$cWss3HuTiAmwxz1/Fxz.G.Y71CXBfvbWdd3UCQPne727hyXez.IeO",
    "photoUrl": "https://images.unsplash.com/photo-1505322747495-6afdd3b70760?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80",
    "serviceType": "Singer",
    "timeAtJob": "1 year 9 months",
    "tagline": "Heres a little diddy",
    "bio": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "workplace": "HOB",
    "accountBalance": 20.19,
    "rating": 4.11,
    "numOfRatings": 10
  },
  {
    "id": 4,
    "username": "TimmyTubo",
    "fullName": "Tim Maitland",
    "password": "$2b$08$jcivtwOmnv19dkK2l.8SoeokmHqqZr6.Ar4ZGJbfniGmSI2IcAZtS",
    "photoUrl": "https://images.unsplash.com/photo-1505322747495-6afdd3b70760?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80",
    "serviceType": "DJ",
    "timeAtJob": "4 years",
    "tagline": "Spinnin!",
    "bio": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "workplace": "Avalon",
    "accountBalance": 90.24,
    "rating": 4.77,
    "numOfRatings": 24
  },
  {
    "id": 5,
    "username": "Geoffry12321",
    "fullName": "Geoff Jeffries",
    "password": "$2b$08$uEkb8GvzX4cckZcIWNDGguRqaAzt7FEbLPJt45K/V27HJV1qZRPf.",
    "photoUrl": "https://images.unsplash.com/photo-1505322747495-6afdd3b70760?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80",
    "serviceType": "Waiter",
    "timeAtJob": "1 year",
    "tagline": "Servin up the sauce!",
    "bio": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "workplace": "fancy restaurant place",
    "accountBalance": 490.04,
    "rating": 4.29,
    "numOfRatings": 62
  },
  {
    "id": 6,
    "username": "test1",
    "fullName": "test",
    "password": "$2b$10$fH38wMtp5l6y4KkIuBQSCO8tUCWB068P60yP1mu4b7CR6peMSdONu",
    "photoUrl": "https://images.unsplash.com/photo-1505322747495-6afdd3b70760?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80",
    "serviceType": "serviceWorkers",
    "timeAtJob": null,
    "tagline": null,
    "bio": null,
    "workplace": null,
    "accountBalance": 0,
    "rating": 5,
    "numOfRatings": 0
  },
  {
    "id": 7,
    "username": "test2",
    "fullName": "test",
    "password": "$2b$10$0bAhPnDmTYo94BT/8ioCcO3q/jqfC7/d6sqEV4TbsB9fc75tmjybu",
    "photoUrl": null,
    "serviceType": "serviceWorkers",
    "timeAtJob": null,
    "tagline": null,
    "bio": null,
    "workplace": null,
    "accountBalance": 0,
    "rating": 5,
    "numOfRatings": 0
  },
  {
    "id": 8,
    "username": "test3",
    "fullName": "test",
    "password": "$2b$10$DsdBvjx/c6SZwASNutBng./Cdr5Bqq8DJKe9ZEgS7FTzuBa4JSDk.",
    "photoUrl": null,
    "serviceType": "serviceWorkers",
    "timeAtJob": null,
    "tagline": null,
    "bio": null,
    "workplace": null,
    "accountBalance": 0,
    "rating": 5,
    "numOfRatings": 0
  },
  {
    "id": 9,
    "username": "test4",
    "fullName": "test",
    "password": "$2b$10$zzTKylsRqrq3EEv7sK/8L.WPPhBVg5fTB4ecd0ezu3pOW6RGOdcoa",
    "photoUrl": "https://images.unsplash.com/photo-1505322747495-6afdd3b70760?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80",
    "serviceType": "serviceWorkers",
    "timeAtJob": null,
    "tagline": null,
    "bio": null,
    "workplace": null,
    "accountBalance": 0,
    "rating": 5,
    "numOfRatings": 0
  },
  {
    "id": 10,
    "username": "test5",
    "fullName": "test",
    "password": "$2b$10$EvO4/rZf8Lxz8DNBNGt5P.lIv3qnZSYUSzqV6zdH.IuOp4ZILSC6e",
    "photoUrl": null,
    "serviceType": "serviceWorkers",
    "timeAtJob": null,
    "tagline": null,
    "bio": null,
    "workplace": null,
    "accountBalance": 0,
    "rating": 5,
    "numOfRatings": 0
  },
  {
    "id": 11,
    "username": "test6",
    "fullName": "test",
    "password": "$2b$10$VBoALSvYV1d4afcyAsQGQOSdDvpsFy5JprHyfnN8bI27PBY3BJf52",
    "photoUrl": null,
    "serviceType": "serviceWorkers",
    "timeAtJob": null,
    "tagline": null,
    "bio": null,
    "workplace": null,
    "accountBalance": 0,
    "rating": 5,
    "numOfRatings": 0
  },
  {
    "id": 12,
    "username": "service",
    "fullName": "Registered service worker",
    "password": "$2b$10$aBzEIi1VNpujNEJNyqwG1OfglSIcFk.gzxR5r1YeX6I8bDFPtPsfi",
    "photoUrl": null,
    "serviceType": "serviceWorker",
    "timeAtJob": null,
    "tagline": null,
    "bio": null,
    "workplace": null,
    "accountBalance": 0,
    "rating": 5,
    "numOfRatings": 0
  },
  {
    "id": 13,
    "username": "service2",
    "fullName": "Registered service worker",
    "password": "$2b$10$vG.8UtSe2peMgXOdLXhscumIT5pmrvoqnPnDOrq927uiYhuZ2hFYy",
    "photoUrl": null,
    "serviceType": "serviceWorker",
    "timeAtJob": null,
    "tagline": null,
    "bio": null,
    "workplace": null,
    "accountBalance": 0,
    "rating": 5,
    "numOfRatings": 0
  }
]